### ISSUE TITLE
One peer appears multiple times

### ISSUE THREAD

**Issue by neworld** [libredrop/libredrop-net#6] opened 2018-12-29 21:07 UTC
I have one peer with 2 connections to the same network. Also, there is emulator and docker stuff:

```
2: wlp59s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9c:b6:d0:b8:4d:b7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.198/24 brd 192.168.5.255 scope global dynamic noprefixroute wlp59s0
       valid_lft 27526sec preferred_lft 27526sec
    inet6 fe80::3f80:fccf:9853:da26/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: enp0s20f0u1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 84:16:f9:17:dc:30 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.192/24 brd 192.168.5.255 scope global dynamic noprefixroute enp0s20f0u1
       valid_lft 27515sec preferred_lft 27515sec
    inet6 fe80::f797:c39:7abc:a401/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:33:6c:04:87 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:33ff:fe6c:487/64 scope link 
       valid_lft forever preferred_lft forever
```

Client gets 3 `PeerInfo` with same public key:

<img src="https://user-images.githubusercontent.com/38703/50542130-2f7e2a00-0bbe-11e9-84af-357bf379f2a5.png" width="250"/>

BTW, last one is virtual device of docker. No idea why peer was discovered through it.

**Comment by povilasb** [comment] 2019-01-12 19:01
1. Every peer might have multiple addresses - as many as networking interfaces,
2. when peer receives broadcasted peer discovery request, it responds with the addresses it's listening on,
3. these are not connections yet, just the addresses that peer will be listening on to establish connections. So multiple addresses is expected behavior.

This is not a bug, closing the issue :)

**Closed as completed by povilasb** 2019-01-12 19:01 UTC
Labels: bug

**Comment by neworld** [comment] 2019-01-12 19:03
Problem is not multiple addresses, but of multiple `PeerInfo` per device.

**Comment by povilasb** [comment] 2019-01-14 18:26
Each `PeerInfo` corresponds to an address, so having multiple addresses implies having multiple `PeerInfo`s. We should identify peers by theyr public keys which is part of `PeerInfo`. Then it should not be a problem, cause we will end up using only a single address.
I will come up with connection implementation that chooses one specific address from many addresses list and upper layers won't have to deal with this :)
